"""empty message

Revision ID: c1d5c010ae28
Revises: 
Create Date: 2022-10-13 16:38:13.008947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d5c010ae28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lister', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('Booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('lister_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lister_name'], ['User.name'], ),
    sa.ForeignKeyConstraint(['requester_name'], ['User.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lister_name'),
    sa.UniqueConstraint('requester_name')
    )
    op.create_table('Business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['owner_name'], ['User.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id'),
    sa.UniqueConstraint('owner_name')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['User.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=120), nullable=False),
    sa.Column('vehicle_manufacturer', sa.String(length=120), nullable=False),
    sa.Column('vehicle_model', sa.String(length=120), nullable=False),
    sa.Column('advertizing_spaces', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['owner_name'], ['User.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('owner_id'),
    sa.UniqueConstraint('owner_name')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['Booking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reviews')
    op.drop_table('Vehicle')
    op.drop_table('Message')
    op.drop_table('Business')
    op.drop_table('Booking')
    op.drop_table('User')
    # ### end Alembic commands ###
